# Generated by Django 2.0.5 on 2018-12-10 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='category_thumbnails')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('pic1', models.ImageField(blank=True, null=True, upload_to='product_pics')),
                ('pic2', models.ImageField(blank=True, null=True, upload_to='product_pics')),
                ('pic3', models.ImageField(blank=True, null=True, upload_to='product_pics')),
                ('pic4', models.ImageField(blank=True, null=True, upload_to='product_pics')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='eco_app.Category')),
            ],
        ),
    ]
